package main

import (
	"net/http"
	"goober-go/internal/handlers"
	"goober-go/internal/services"
	"goober-go/internal/repository"
)

func registerInternalRoutes(mux *http.ServeMux) {
	handlers.NewAccountHandler("/api/account").RegisterRoutes(mux)
	handlers.NewBudgetHandler("/api/budget").RegisterRoutes(mux)
	handlers.NewCampaignHandler("/api/campaign").RegisterRoutes(mux)
	handlers.NewCategoryHandler("/api/category").RegisterRoutes(mux)
	handlers.NewCommentHandler("/api/comment").RegisterRoutes(mux)
	handlers.NewCustomerHandler("/api/customer").RegisterRoutes(mux)
	handlers.NewDepartmentHandler("/api/department").RegisterRoutes(mux)
	handlers.NewDiscountHandler("/api/discount").RegisterRoutes(mux)
	handlers.NewEmployeeHandler("/api/employee").RegisterRoutes(mux)
	handlers.NewExpenseHandler("/api/expense").RegisterRoutes(mux)
	handlers.NewInvoiceHandler("/api/invoice").RegisterRoutes(mux)
	handlers.NewMilestoneHandler("/api/milestone").RegisterRoutes(mux)
	handlers.NewNotificationHandler("/api/notification").RegisterRoutes(mux)
	handlers.NewOrderHandler("/api/order").RegisterRoutes(mux)
	handlers.NewPaymentHandler("/api/payment").RegisterRoutes(mux)
	handlers.NewProductHandler("/api/product").RegisterRoutes(mux)
	handlers.NewProjectHandler("/api/project").RegisterRoutes(mux)
	handlers.NewReviewHandler("/api/review").RegisterRoutes(mux)
	handlers.NewShipmentHandler("/api/shipment").RegisterRoutes(mux)
	handlers.NewSubscriptionHandler("/api/subscription").RegisterRoutes(mux)
	handlers.NewTaskHandler("/api/task").RegisterRoutes(mux)
	handlers.NewTicketHandler("/api/ticket").RegisterRoutes(mux)
	handlers.NewTransactionHandler("/api/transaction").RegisterRoutes(mux)
	handlers.NewUserHandler("/api/user").RegisterRoutes(mux)
	handlers.NewWarehouseHandler("/api/warehouse").RegisterRoutes(mux)

	_ = services.NewBudgetService()
	_ = services.NewCampaignService()
	_ = services.NewCategoryService()
	_ = services.NewCommentService()
	_ = services.NewCustomerService()
	_ = services.NewDepartmentService()
	_ = services.NewDiscountService()
	_ = services.NewEmployeeService()
	_ = services.NewExpenseService()
	_ = services.NewInvoiceService()
	_ = services.NewMilestoneService()
	_ = services.NewNotificationService()
	_ = services.NewOrderService()
	_ = services.NewPaymentService()
	_ = services.NewProductService()
	_ = services.NewProjectService()
	_ = services.NewReviewService()
	_ = services.NewShipmentService()
	_ = services.NewSubscriptionService()
	_ = services.NewTaskService()
	_ = services.NewTicketService()
	_ = services.NewTransactionService()
	_ = services.NewUserService()
	_ = services.NewWarehouseService()

	_ = repository.NewBudgetRepository()
	_ = repository.NewCampaignRepository()
	_ = repository.NewCategoryRepository()
	_ = repository.NewCommentRepository()
	_ = repository.NewCustomerRepository()
	_ = repository.NewDepartmentRepository()
	_ = repository.NewDiscountRepository()
	_ = repository.NewEmployeeRepository()
	_ = repository.NewExpenseRepository()
	_ = repository.NewInvoiceRepository()
	_ = repository.NewMilestoneRepository()
	_ = repository.NewNotificationRepository()
	_ = repository.NewOrderRepository()
	_ = repository.NewPaymentRepository()
	_ = repository.NewProductRepository()
	_ = repository.NewProjectRepository()
	_ = repository.NewReviewRepository()
	_ = repository.NewShipmentRepository()
	_ = repository.NewSubscriptionRepository()
	_ = repository.NewTaskRepository()
	_ = repository.NewTicketRepository()
	_ = repository.NewTransactionRepository()
	_ = repository.NewUserRepository()
	_ = repository.NewWarehouseRepository()
}
