package main

import (
	"net/http"
	"goober-go/internal/handlers"
	"goober-go/internal/services"
	"goober-go/internal/repository"
)

func registerInternalRoutes(mux *http.ServeMux) {
	handlers.NewAccountHandler("/api/account").RegisterRoutes(mux)
	handlers.NewAchievementHandler("/api/achievement").RegisterRoutes(mux)
	handlers.NewAlertHandler("/api/alert").RegisterRoutes(mux)
	handlers.NewAudienceHandler("/api/audience").RegisterRoutes(mux)
	handlers.NewBillingAccountHandler("/api/billing_account").RegisterRoutes(mux)
	handlers.NewBillingAchievementHandler("/api/billing_achievement").RegisterRoutes(mux)
	handlers.NewBillingAlertHandler("/api/billing_alert").RegisterRoutes(mux)
	handlers.NewBillingAudienceHandler("/api/billing_audience").RegisterRoutes(mux)
	handlers.NewBillingBookingHandler("/api/billing_booking").RegisterRoutes(mux)
	handlers.NewBillingBudgetHandler("/api/billing_budget").RegisterRoutes(mux)
	handlers.NewBillingCampaignHandler("/api/billing_campaign").RegisterRoutes(mux)
	handlers.NewBillingCategoryHandler("/api/billing_category").RegisterRoutes(mux)
	handlers.NewBillingCertificateHandler("/api/billing_certificate").RegisterRoutes(mux)
	handlers.NewBillingChannelHandler("/api/billing_channel").RegisterRoutes(mux)
	handlers.NewBillingCommentHandler("/api/billing_comment").RegisterRoutes(mux)
	handlers.NewBillingContractHandler("/api/billing_contract").RegisterRoutes(mux)
	handlers.NewBillingCustomerHandler("/api/billing_customer").RegisterRoutes(mux)
	handlers.NewBillingDepartmentHandler("/api/billing_department").RegisterRoutes(mux)
	handlers.NewBillingDeploymentHandler("/api/billing_deployment").RegisterRoutes(mux)
	handlers.NewBillingDiscountHandler("/api/billing_discount").RegisterRoutes(mux)
	handlers.NewBillingDocumentHandler("/api/billing_document").RegisterRoutes(mux)
	handlers.NewBillingEmployeeHandler("/api/billing_employee").RegisterRoutes(mux)
	handlers.NewBillingEndpointHandler("/api/billing_endpoint").RegisterRoutes(mux)
	handlers.NewBillingEventHandler("/api/billing_event").RegisterRoutes(mux)
	handlers.NewBillingExpenseHandler("/api/billing_expense").RegisterRoutes(mux)
	handlers.NewBillingExperimentHandler("/api/billing_experiment").RegisterRoutes(mux)
	handlers.NewBillingFeatureHandler("/api/billing_feature").RegisterRoutes(mux)
	handlers.NewBillingFeedbackHandler("/api/billing_feedback").RegisterRoutes(mux)
	handlers.NewBillingInvoiceHandler("/api/billing_invoice").RegisterRoutes(mux)
	handlers.NewBillingLeadHandler("/api/billing_lead").RegisterRoutes(mux)
	handlers.NewBillingMessageHandler("/api/billing_message").RegisterRoutes(mux)
	handlers.NewBillingMetricHandler("/api/billing_metric").RegisterRoutes(mux)
	handlers.NewBillingMilestoneHandler("/api/billing_milestone").RegisterRoutes(mux)
	handlers.NewBillingNotificationHandler("/api/billing_notification").RegisterRoutes(mux)
	handlers.NewBillingOrderHandler("/api/billing_order").RegisterRoutes(mux)
	handlers.NewBillingOrganizationHandler("/api/billing_organization").RegisterRoutes(mux)
	handlers.NewBillingPaymentHandler("/api/billing_payment").RegisterRoutes(mux)
	handlers.NewBillingPermissionHandler("/api/billing_permission").RegisterRoutes(mux)
	handlers.NewBillingPipelineHandler("/api/billing_pipeline").RegisterRoutes(mux)
	handlers.NewBillingPolicyHandler("/api/billing_policy").RegisterRoutes(mux)
	handlers.NewBillingProductHandler("/api/billing_product").RegisterRoutes(mux)
	handlers.NewBillingProjectHandler("/api/billing_project").RegisterRoutes(mux)
	handlers.NewBillingQuotaHandler("/api/billing_quota").RegisterRoutes(mux)
	handlers.NewBillingReservationHandler("/api/billing_reservation").RegisterRoutes(mux)
	handlers.NewBillingReviewHandler("/api/billing_review").RegisterRoutes(mux)
	handlers.NewBillingRewardHandler("/api/billing_reward").RegisterRoutes(mux)
	handlers.NewBillingRoleHandler("/api/billing_role").RegisterRoutes(mux)
	handlers.NewBillingRuleHandler("/api/billing_rule").RegisterRoutes(mux)
	handlers.NewBillingScheduleHandler("/api/billing_schedule").RegisterRoutes(mux)
	handlers.NewBillingSegmentHandler("/api/billing_segment").RegisterRoutes(mux)
	handlers.NewBillingSessionHandler("/api/billing_session").RegisterRoutes(mux)
	handlers.NewBillingShipmentHandler("/api/billing_shipment").RegisterRoutes(mux)
	handlers.NewBillingSnapshotHandler("/api/billing_snapshot").RegisterRoutes(mux)
	handlers.NewBillingSubscriptionHandler("/api/billing_subscription").RegisterRoutes(mux)
	handlers.NewBillingSurveyHandler("/api/billing_survey").RegisterRoutes(mux)
	handlers.NewBillingTaskHandler("/api/billing_task").RegisterRoutes(mux)
	handlers.NewBillingTeamHandler("/api/billing_team").RegisterRoutes(mux)
	handlers.NewBillingTemplateHandler("/api/billing_template").RegisterRoutes(mux)
	handlers.NewBillingTicketHandler("/api/billing_ticket").RegisterRoutes(mux)
	handlers.NewBillingTransactionHandler("/api/billing_transaction").RegisterRoutes(mux)
	handlers.NewBillingUserHandler("/api/billing_user").RegisterRoutes(mux)
	handlers.NewBillingVenueHandler("/api/billing_venue").RegisterRoutes(mux)
	handlers.NewBillingWarehouseHandler("/api/billing_warehouse").RegisterRoutes(mux)
	handlers.NewBillingWebhookHandler("/api/billing_webhook").RegisterRoutes(mux)
	handlers.NewBillingWorkflowHandler("/api/billing_workflow").RegisterRoutes(mux)
	handlers.NewBookingHandler("/api/booking").RegisterRoutes(mux)
	handlers.NewBudgetHandler("/api/budget").RegisterRoutes(mux)
	handlers.NewCampaignHandler("/api/campaign").RegisterRoutes(mux)
	handlers.NewCategoryHandler("/api/category").RegisterRoutes(mux)
	handlers.NewCertificateHandler("/api/certificate").RegisterRoutes(mux)
	handlers.NewChannelHandler("/api/channel").RegisterRoutes(mux)
	handlers.NewCommentHandler("/api/comment").RegisterRoutes(mux)
	handlers.NewContractHandler("/api/contract").RegisterRoutes(mux)
	handlers.NewCustomerHandler("/api/customer").RegisterRoutes(mux)
	handlers.NewDepartmentHandler("/api/department").RegisterRoutes(mux)
	handlers.NewDeploymentHandler("/api/deployment").RegisterRoutes(mux)
	handlers.NewDiscountHandler("/api/discount").RegisterRoutes(mux)
	handlers.NewDocumentHandler("/api/document").RegisterRoutes(mux)
	handlers.NewEmployeeHandler("/api/employee").RegisterRoutes(mux)
	handlers.NewEndpointHandler("/api/endpoint").RegisterRoutes(mux)
	handlers.NewEventHandler("/api/event").RegisterRoutes(mux)
	handlers.NewExpenseHandler("/api/expense").RegisterRoutes(mux)
	handlers.NewExperimentHandler("/api/experiment").RegisterRoutes(mux)
	handlers.NewFeatureHandler("/api/feature").RegisterRoutes(mux)
	handlers.NewFeedbackHandler("/api/feedback").RegisterRoutes(mux)
	handlers.NewInventoryAccountHandler("/api/inventory_account").RegisterRoutes(mux)
	handlers.NewInventoryAchievementHandler("/api/inventory_achievement").RegisterRoutes(mux)
	handlers.NewInventoryAlertHandler("/api/inventory_alert").RegisterRoutes(mux)
	handlers.NewInventoryBookingHandler("/api/inventory_booking").RegisterRoutes(mux)
	handlers.NewInventoryBudgetHandler("/api/inventory_budget").RegisterRoutes(mux)
	handlers.NewInventoryCampaignHandler("/api/inventory_campaign").RegisterRoutes(mux)
	handlers.NewInventoryCategoryHandler("/api/inventory_category").RegisterRoutes(mux)
	handlers.NewInventoryCertificateHandler("/api/inventory_certificate").RegisterRoutes(mux)
	handlers.NewInventoryChannelHandler("/api/inventory_channel").RegisterRoutes(mux)
	handlers.NewInventoryCommentHandler("/api/inventory_comment").RegisterRoutes(mux)
	handlers.NewInventoryCustomerHandler("/api/inventory_customer").RegisterRoutes(mux)
	handlers.NewInventoryDepartmentHandler("/api/inventory_department").RegisterRoutes(mux)
	handlers.NewInventoryDeploymentHandler("/api/inventory_deployment").RegisterRoutes(mux)
	handlers.NewInventoryDiscountHandler("/api/inventory_discount").RegisterRoutes(mux)
	handlers.NewInventoryEmployeeHandler("/api/inventory_employee").RegisterRoutes(mux)
	handlers.NewInventoryEndpointHandler("/api/inventory_endpoint").RegisterRoutes(mux)
	handlers.NewInventoryEventHandler("/api/inventory_event").RegisterRoutes(mux)
	handlers.NewInventoryExpenseHandler("/api/inventory_expense").RegisterRoutes(mux)
	handlers.NewInventoryFeatureHandler("/api/inventory_feature").RegisterRoutes(mux)
	handlers.NewInventoryFeedbackHandler("/api/inventory_feedback").RegisterRoutes(mux)
	handlers.NewInventoryInvoiceHandler("/api/inventory_invoice").RegisterRoutes(mux)
	handlers.NewInventoryMessageHandler("/api/inventory_message").RegisterRoutes(mux)
	handlers.NewInventoryMetricHandler("/api/inventory_metric").RegisterRoutes(mux)
	handlers.NewInventoryMilestoneHandler("/api/inventory_milestone").RegisterRoutes(mux)
	handlers.NewInventoryNotificationHandler("/api/inventory_notification").RegisterRoutes(mux)
	handlers.NewInventoryOrderHandler("/api/inventory_order").RegisterRoutes(mux)
	handlers.NewInventoryOrganizationHandler("/api/inventory_organization").RegisterRoutes(mux)
	handlers.NewInventoryPaymentHandler("/api/inventory_payment").RegisterRoutes(mux)
	handlers.NewInventoryPermissionHandler("/api/inventory_permission").RegisterRoutes(mux)
	handlers.NewInventoryPipelineHandler("/api/inventory_pipeline").RegisterRoutes(mux)
	handlers.NewInventoryPolicyHandler("/api/inventory_policy").RegisterRoutes(mux)
	handlers.NewInventoryProductHandler("/api/inventory_product").RegisterRoutes(mux)
	handlers.NewInventoryProjectHandler("/api/inventory_project").RegisterRoutes(mux)
	handlers.NewInventoryQuotaHandler("/api/inventory_quota").RegisterRoutes(mux)
	handlers.NewInventoryReservationHandler("/api/inventory_reservation").RegisterRoutes(mux)
	handlers.NewInventoryReviewHandler("/api/inventory_review").RegisterRoutes(mux)
	handlers.NewInventoryRewardHandler("/api/inventory_reward").RegisterRoutes(mux)
	handlers.NewInventoryRoleHandler("/api/inventory_role").RegisterRoutes(mux)
	handlers.NewInventoryRuleHandler("/api/inventory_rule").RegisterRoutes(mux)
	handlers.NewInventoryScheduleHandler("/api/inventory_schedule").RegisterRoutes(mux)
	handlers.NewInventorySessionHandler("/api/inventory_session").RegisterRoutes(mux)
	handlers.NewInventoryShipmentHandler("/api/inventory_shipment").RegisterRoutes(mux)
	handlers.NewInventorySnapshotHandler("/api/inventory_snapshot").RegisterRoutes(mux)
	handlers.NewInventorySubscriptionHandler("/api/inventory_subscription").RegisterRoutes(mux)
	handlers.NewInventorySurveyHandler("/api/inventory_survey").RegisterRoutes(mux)
	handlers.NewInventoryTaskHandler("/api/inventory_task").RegisterRoutes(mux)
	handlers.NewInventoryTeamHandler("/api/inventory_team").RegisterRoutes(mux)
	handlers.NewInventoryTemplateHandler("/api/inventory_template").RegisterRoutes(mux)
	handlers.NewInventoryTicketHandler("/api/inventory_ticket").RegisterRoutes(mux)
	handlers.NewInventoryTransactionHandler("/api/inventory_transaction").RegisterRoutes(mux)
	handlers.NewInventoryUserHandler("/api/inventory_user").RegisterRoutes(mux)
	handlers.NewInventoryVenueHandler("/api/inventory_venue").RegisterRoutes(mux)
	handlers.NewInventoryWarehouseHandler("/api/inventory_warehouse").RegisterRoutes(mux)
	handlers.NewInventoryWebhookHandler("/api/inventory_webhook").RegisterRoutes(mux)
	handlers.NewInventoryWorkflowHandler("/api/inventory_workflow").RegisterRoutes(mux)
	handlers.NewInvoiceHandler("/api/invoice").RegisterRoutes(mux)
	handlers.NewLeadHandler("/api/lead").RegisterRoutes(mux)
	handlers.NewMessageHandler("/api/message").RegisterRoutes(mux)
	handlers.NewMetricHandler("/api/metric").RegisterRoutes(mux)
	handlers.NewMilestoneHandler("/api/milestone").RegisterRoutes(mux)
	handlers.NewNotificationHandler("/api/notification").RegisterRoutes(mux)
	handlers.NewOrderHandler("/api/order").RegisterRoutes(mux)
	handlers.NewOrganizationHandler("/api/organization").RegisterRoutes(mux)
	handlers.NewPaymentHandler("/api/payment").RegisterRoutes(mux)
	handlers.NewPermissionHandler("/api/permission").RegisterRoutes(mux)
	handlers.NewPipelineHandler("/api/pipeline").RegisterRoutes(mux)
	handlers.NewPolicyHandler("/api/policy").RegisterRoutes(mux)
	handlers.NewProductHandler("/api/product").RegisterRoutes(mux)
	handlers.NewProjectHandler("/api/project").RegisterRoutes(mux)
	handlers.NewQuotaHandler("/api/quota").RegisterRoutes(mux)
	handlers.NewReservationHandler("/api/reservation").RegisterRoutes(mux)
	handlers.NewReviewHandler("/api/review").RegisterRoutes(mux)
	handlers.NewRewardHandler("/api/reward").RegisterRoutes(mux)
	handlers.NewRoleHandler("/api/role").RegisterRoutes(mux)
	handlers.NewRuleHandler("/api/rule").RegisterRoutes(mux)
	handlers.NewScheduleHandler("/api/schedule").RegisterRoutes(mux)
	handlers.NewSegmentHandler("/api/segment").RegisterRoutes(mux)
	handlers.NewSessionHandler("/api/session").RegisterRoutes(mux)
	handlers.NewShipmentHandler("/api/shipment").RegisterRoutes(mux)
	handlers.NewShippingAccountHandler("/api/shipping_account").RegisterRoutes(mux)
	handlers.NewShippingAchievementHandler("/api/shipping_achievement").RegisterRoutes(mux)
	handlers.NewShippingAlertHandler("/api/shipping_alert").RegisterRoutes(mux)
	handlers.NewShippingAudienceHandler("/api/shipping_audience").RegisterRoutes(mux)
	handlers.NewShippingBookingHandler("/api/shipping_booking").RegisterRoutes(mux)
	handlers.NewShippingBudgetHandler("/api/shipping_budget").RegisterRoutes(mux)
	handlers.NewShippingCampaignHandler("/api/shipping_campaign").RegisterRoutes(mux)
	handlers.NewShippingCategoryHandler("/api/shipping_category").RegisterRoutes(mux)
	handlers.NewShippingCertificateHandler("/api/shipping_certificate").RegisterRoutes(mux)
	handlers.NewShippingChannelHandler("/api/shipping_channel").RegisterRoutes(mux)
	handlers.NewShippingCommentHandler("/api/shipping_comment").RegisterRoutes(mux)
	handlers.NewShippingContractHandler("/api/shipping_contract").RegisterRoutes(mux)
	handlers.NewShippingCustomerHandler("/api/shipping_customer").RegisterRoutes(mux)
	handlers.NewShippingDepartmentHandler("/api/shipping_department").RegisterRoutes(mux)
	handlers.NewShippingDeploymentHandler("/api/shipping_deployment").RegisterRoutes(mux)
	handlers.NewShippingDiscountHandler("/api/shipping_discount").RegisterRoutes(mux)
	handlers.NewShippingDocumentHandler("/api/shipping_document").RegisterRoutes(mux)
	handlers.NewShippingEmployeeHandler("/api/shipping_employee").RegisterRoutes(mux)
	handlers.NewShippingEndpointHandler("/api/shipping_endpoint").RegisterRoutes(mux)
	handlers.NewShippingEventHandler("/api/shipping_event").RegisterRoutes(mux)
	handlers.NewShippingExpenseHandler("/api/shipping_expense").RegisterRoutes(mux)
	handlers.NewShippingExperimentHandler("/api/shipping_experiment").RegisterRoutes(mux)
	handlers.NewShippingFeatureHandler("/api/shipping_feature").RegisterRoutes(mux)
	handlers.NewShippingFeedbackHandler("/api/shipping_feedback").RegisterRoutes(mux)
	handlers.NewShippingInvoiceHandler("/api/shipping_invoice").RegisterRoutes(mux)
	handlers.NewShippingLeadHandler("/api/shipping_lead").RegisterRoutes(mux)
	handlers.NewShippingMessageHandler("/api/shipping_message").RegisterRoutes(mux)
	handlers.NewShippingMetricHandler("/api/shipping_metric").RegisterRoutes(mux)
	handlers.NewShippingMilestoneHandler("/api/shipping_milestone").RegisterRoutes(mux)
	handlers.NewShippingNotificationHandler("/api/shipping_notification").RegisterRoutes(mux)
	handlers.NewShippingOrderHandler("/api/shipping_order").RegisterRoutes(mux)
	handlers.NewShippingOrganizationHandler("/api/shipping_organization").RegisterRoutes(mux)
	handlers.NewShippingPaymentHandler("/api/shipping_payment").RegisterRoutes(mux)
	handlers.NewShippingPermissionHandler("/api/shipping_permission").RegisterRoutes(mux)
	handlers.NewShippingPipelineHandler("/api/shipping_pipeline").RegisterRoutes(mux)
	handlers.NewShippingPolicyHandler("/api/shipping_policy").RegisterRoutes(mux)
	handlers.NewShippingProductHandler("/api/shipping_product").RegisterRoutes(mux)
	handlers.NewShippingProjectHandler("/api/shipping_project").RegisterRoutes(mux)
	handlers.NewShippingQuotaHandler("/api/shipping_quota").RegisterRoutes(mux)
	handlers.NewShippingReservationHandler("/api/shipping_reservation").RegisterRoutes(mux)
	handlers.NewShippingReviewHandler("/api/shipping_review").RegisterRoutes(mux)
	handlers.NewShippingRewardHandler("/api/shipping_reward").RegisterRoutes(mux)
	handlers.NewShippingRoleHandler("/api/shipping_role").RegisterRoutes(mux)
	handlers.NewShippingRuleHandler("/api/shipping_rule").RegisterRoutes(mux)
	handlers.NewShippingScheduleHandler("/api/shipping_schedule").RegisterRoutes(mux)
	handlers.NewShippingSegmentHandler("/api/shipping_segment").RegisterRoutes(mux)
	handlers.NewShippingSessionHandler("/api/shipping_session").RegisterRoutes(mux)
	handlers.NewShippingShipmentHandler("/api/shipping_shipment").RegisterRoutes(mux)
	handlers.NewShippingSnapshotHandler("/api/shipping_snapshot").RegisterRoutes(mux)
	handlers.NewShippingSubscriptionHandler("/api/shipping_subscription").RegisterRoutes(mux)
	handlers.NewShippingSurveyHandler("/api/shipping_survey").RegisterRoutes(mux)
	handlers.NewShippingTaskHandler("/api/shipping_task").RegisterRoutes(mux)
	handlers.NewShippingTeamHandler("/api/shipping_team").RegisterRoutes(mux)
	handlers.NewShippingTemplateHandler("/api/shipping_template").RegisterRoutes(mux)
	handlers.NewShippingTicketHandler("/api/shipping_ticket").RegisterRoutes(mux)
	handlers.NewShippingTransactionHandler("/api/shipping_transaction").RegisterRoutes(mux)
	handlers.NewShippingUserHandler("/api/shipping_user").RegisterRoutes(mux)
	handlers.NewShippingVenueHandler("/api/shipping_venue").RegisterRoutes(mux)
	handlers.NewShippingWarehouseHandler("/api/shipping_warehouse").RegisterRoutes(mux)
	handlers.NewShippingWebhookHandler("/api/shipping_webhook").RegisterRoutes(mux)
	handlers.NewShippingWorkflowHandler("/api/shipping_workflow").RegisterRoutes(mux)
	handlers.NewSnapshotHandler("/api/snapshot").RegisterRoutes(mux)
	handlers.NewSubscriptionHandler("/api/subscription").RegisterRoutes(mux)
	handlers.NewSurveyHandler("/api/survey").RegisterRoutes(mux)
	handlers.NewTaskHandler("/api/task").RegisterRoutes(mux)
	handlers.NewTeamHandler("/api/team").RegisterRoutes(mux)
	handlers.NewTemplateHandler("/api/template").RegisterRoutes(mux)
	handlers.NewTicketHandler("/api/ticket").RegisterRoutes(mux)
	handlers.NewTransactionHandler("/api/transaction").RegisterRoutes(mux)
	handlers.NewUserHandler("/api/user").RegisterRoutes(mux)
	handlers.NewVenueHandler("/api/venue").RegisterRoutes(mux)
	handlers.NewWarehouseHandler("/api/warehouse").RegisterRoutes(mux)
	handlers.NewWebhookHandler("/api/webhook").RegisterRoutes(mux)
	handlers.NewWorkflowHandler("/api/workflow").RegisterRoutes(mux)

	_ = services.NewAccountService()
	_ = services.NewAchievementService()
	_ = services.NewAlertService()
	_ = services.NewAudienceService()
	_ = services.NewBillingAccountService()
	_ = services.NewBillingAchievementService()
	_ = services.NewBillingAlertService()
	_ = services.NewBillingAudienceService()
	_ = services.NewBillingBookingService()
	_ = services.NewBillingBudgetService()
	_ = services.NewBillingCampaignService()
	_ = services.NewBillingCategoryService()
	_ = services.NewBillingCertificateService()
	_ = services.NewBillingChannelService()
	_ = services.NewBillingCommentService()
	_ = services.NewBillingContractService()
	_ = services.NewBillingCustomerService()
	_ = services.NewBillingDepartmentService()
	_ = services.NewBillingDeploymentService()
	_ = services.NewBillingDiscountService()
	_ = services.NewBillingDocumentService()
	_ = services.NewBillingEmployeeService()
	_ = services.NewBillingEndpointService()
	_ = services.NewBillingEventService()
	_ = services.NewBillingExpenseService()
	_ = services.NewBillingExperimentService()
	_ = services.NewBillingFeatureService()
	_ = services.NewBillingFeedbackService()
	_ = services.NewBillingInvoiceService()
	_ = services.NewBillingLeadService()
	_ = services.NewBillingMessageService()
	_ = services.NewBillingMetricService()
	_ = services.NewBillingMilestoneService()
	_ = services.NewBillingNotificationService()
	_ = services.NewBillingOrderService()
	_ = services.NewBillingOrganizationService()
	_ = services.NewBillingPaymentService()
	_ = services.NewBillingPermissionService()
	_ = services.NewBillingPipelineService()
	_ = services.NewBillingPolicyService()
	_ = services.NewBillingProductService()
	_ = services.NewBillingProjectService()
	_ = services.NewBillingQuotaService()
	_ = services.NewBillingReservationService()
	_ = services.NewBillingReviewService()
	_ = services.NewBillingRewardService()
	_ = services.NewBillingRoleService()
	_ = services.NewBillingRuleService()
	_ = services.NewBillingScheduleService()
	_ = services.NewBillingSegmentService()
	_ = services.NewBillingSessionService()
	_ = services.NewBillingShipmentService()
	_ = services.NewBillingSnapshotService()
	_ = services.NewBillingSubscriptionService()
	_ = services.NewBillingSurveyService()
	_ = services.NewBillingTaskService()
	_ = services.NewBillingTeamService()
	_ = services.NewBillingTemplateService()
	_ = services.NewBillingTicketService()
	_ = services.NewBillingTransactionService()
	_ = services.NewBillingUserService()
	_ = services.NewBillingVenueService()
	_ = services.NewBillingWarehouseService()
	_ = services.NewBillingWebhookService()
	_ = services.NewBillingWorkflowService()
	_ = services.NewBookingService()
	_ = services.NewBudgetService()
	_ = services.NewCampaignService()
	_ = services.NewCategoryService()
	_ = services.NewCertificateService()
	_ = services.NewChannelService()
	_ = services.NewCommentService()
	_ = services.NewContractService()
	_ = services.NewCustomerService()
	_ = services.NewDepartmentService()
	_ = services.NewDeploymentService()
	_ = services.NewDiscountService()
	_ = services.NewDocumentService()
	_ = services.NewEmployeeService()
	_ = services.NewEndpointService()
	_ = services.NewEventService()
	_ = services.NewExpenseService()
	_ = services.NewExperimentService()
	_ = services.NewFeatureService()
	_ = services.NewFeedbackService()
	_ = services.NewInventoryAccountService()
	_ = services.NewInventoryAchievementService()
	_ = services.NewInventoryAlertService()
	_ = services.NewInventoryBookingService()
	_ = services.NewInventoryBudgetService()
	_ = services.NewInventoryCampaignService()
	_ = services.NewInventoryCategoryService()
	_ = services.NewInventoryCertificateService()
	_ = services.NewInventoryChannelService()
	_ = services.NewInventoryCommentService()
	_ = services.NewInventoryCustomerService()
	_ = services.NewInventoryDepartmentService()
	_ = services.NewInventoryDeploymentService()
	_ = services.NewInventoryDiscountService()
	_ = services.NewInventoryEmployeeService()
	_ = services.NewInventoryEndpointService()
	_ = services.NewInventoryEventService()
	_ = services.NewInventoryExpenseService()
	_ = services.NewInventoryFeatureService()
	_ = services.NewInventoryFeedbackService()
	_ = services.NewInventoryInvoiceService()
	_ = services.NewInventoryMessageService()
	_ = services.NewInventoryMetricService()
	_ = services.NewInventoryMilestoneService()
	_ = services.NewInventoryNotificationService()
	_ = services.NewInventoryOrderService()
	_ = services.NewInventoryOrganizationService()
	_ = services.NewInventoryPaymentService()
	_ = services.NewInventoryPermissionService()
	_ = services.NewInventoryPipelineService()
	_ = services.NewInventoryPolicyService()
	_ = services.NewInventoryProductService()
	_ = services.NewInventoryProjectService()
	_ = services.NewInventoryQuotaService()
	_ = services.NewInventoryReservationService()
	_ = services.NewInventoryReviewService()
	_ = services.NewInventoryRewardService()
	_ = services.NewInventoryRoleService()
	_ = services.NewInventoryRuleService()
	_ = services.NewInventoryScheduleService()
	_ = services.NewInventorySessionService()
	_ = services.NewInventoryShipmentService()
	_ = services.NewInventorySnapshotService()
	_ = services.NewInventorySubscriptionService()
	_ = services.NewInventorySurveyService()
	_ = services.NewInventoryTaskService()
	_ = services.NewInventoryTeamService()
	_ = services.NewInventoryTemplateService()
	_ = services.NewInventoryTicketService()
	_ = services.NewInventoryTransactionService()
	_ = services.NewInventoryUserService()
	_ = services.NewInventoryVenueService()
	_ = services.NewInventoryWarehouseService()
	_ = services.NewInventoryWebhookService()
	_ = services.NewInventoryWorkflowService()
	_ = services.NewInvoiceService()
	_ = services.NewLeadService()
	_ = services.NewMessageService()
	_ = services.NewMetricService()
	_ = services.NewMilestoneService()
	_ = services.NewNotificationService()
	_ = services.NewOrderService()
	_ = services.NewOrganizationService()
	_ = services.NewPaymentService()
	_ = services.NewPermissionService()
	_ = services.NewPipelineService()
	_ = services.NewPolicyService()
	_ = services.NewProductService()
	_ = services.NewProjectService()
	_ = services.NewQuotaService()
	_ = services.NewReservationService()
	_ = services.NewReviewService()
	_ = services.NewRewardService()
	_ = services.NewRoleService()
	_ = services.NewRuleService()
	_ = services.NewScheduleService()
	_ = services.NewSegmentService()
	_ = services.NewSessionService()
	_ = services.NewShipmentService()
	_ = services.NewShippingAccountService()
	_ = services.NewShippingAchievementService()
	_ = services.NewShippingAlertService()
	_ = services.NewShippingAudienceService()
	_ = services.NewShippingBookingService()
	_ = services.NewShippingBudgetService()
	_ = services.NewShippingCampaignService()
	_ = services.NewShippingCategoryService()
	_ = services.NewShippingCertificateService()
	_ = services.NewShippingChannelService()
	_ = services.NewShippingCommentService()
	_ = services.NewShippingContractService()
	_ = services.NewShippingCustomerService()
	_ = services.NewShippingDepartmentService()
	_ = services.NewShippingDeploymentService()
	_ = services.NewShippingDiscountService()
	_ = services.NewShippingDocumentService()
	_ = services.NewShippingEmployeeService()
	_ = services.NewShippingEndpointService()
	_ = services.NewShippingEventService()
	_ = services.NewShippingExpenseService()
	_ = services.NewShippingExperimentService()
	_ = services.NewShippingFeatureService()
	_ = services.NewShippingFeedbackService()
	_ = services.NewShippingInvoiceService()
	_ = services.NewShippingLeadService()
	_ = services.NewShippingMessageService()
	_ = services.NewShippingMetricService()
	_ = services.NewShippingMilestoneService()
	_ = services.NewShippingNotificationService()
	_ = services.NewShippingOrderService()
	_ = services.NewShippingOrganizationService()
	_ = services.NewShippingPaymentService()
	_ = services.NewShippingPermissionService()
	_ = services.NewShippingPipelineService()
	_ = services.NewShippingPolicyService()
	_ = services.NewShippingProductService()
	_ = services.NewShippingProjectService()
	_ = services.NewShippingQuotaService()
	_ = services.NewShippingReservationService()
	_ = services.NewShippingReviewService()
	_ = services.NewShippingRewardService()
	_ = services.NewShippingRoleService()
	_ = services.NewShippingRuleService()
	_ = services.NewShippingScheduleService()
	_ = services.NewShippingSegmentService()
	_ = services.NewShippingSessionService()
	_ = services.NewShippingShipmentService()
	_ = services.NewShippingSnapshotService()
	_ = services.NewShippingSubscriptionService()
	_ = services.NewShippingSurveyService()
	_ = services.NewShippingTaskService()
	_ = services.NewShippingTeamService()
	_ = services.NewShippingTemplateService()
	_ = services.NewShippingTicketService()
	_ = services.NewShippingTransactionService()
	_ = services.NewShippingUserService()
	_ = services.NewShippingVenueService()
	_ = services.NewShippingWarehouseService()
	_ = services.NewShippingWebhookService()
	_ = services.NewShippingWorkflowService()
	_ = services.NewSnapshotService()
	_ = services.NewSubscriptionService()
	_ = services.NewSurveyService()
	_ = services.NewTaskService()
	_ = services.NewTeamService()
	_ = services.NewTemplateService()
	_ = services.NewTicketService()
	_ = services.NewTransactionService()
	_ = services.NewUserService()
	_ = services.NewVenueService()
	_ = services.NewWarehouseService()
	_ = services.NewWebhookService()
	_ = services.NewWorkflowService()

	_ = repository.NewAccountRepository()
	_ = repository.NewAchievementRepository()
	_ = repository.NewAlertRepository()
	_ = repository.NewAudienceRepository()
	_ = repository.NewBillingAccountRepository()
	_ = repository.NewBillingAchievementRepository()
	_ = repository.NewBillingAlertRepository()
	_ = repository.NewBillingAudienceRepository()
	_ = repository.NewBillingBookingRepository()
	_ = repository.NewBillingBudgetRepository()
	_ = repository.NewBillingCampaignRepository()
	_ = repository.NewBillingCategoryRepository()
	_ = repository.NewBillingCertificateRepository()
	_ = repository.NewBillingChannelRepository()
	_ = repository.NewBillingCommentRepository()
	_ = repository.NewBillingContractRepository()
	_ = repository.NewBillingCustomerRepository()
	_ = repository.NewBillingDepartmentRepository()
	_ = repository.NewBillingDeploymentRepository()
	_ = repository.NewBillingDiscountRepository()
	_ = repository.NewBillingDocumentRepository()
	_ = repository.NewBillingEmployeeRepository()
	_ = repository.NewBillingEndpointRepository()
	_ = repository.NewBillingEventRepository()
	_ = repository.NewBillingExpenseRepository()
	_ = repository.NewBillingExperimentRepository()
	_ = repository.NewBillingFeatureRepository()
	_ = repository.NewBillingFeedbackRepository()
	_ = repository.NewBillingInvoiceRepository()
	_ = repository.NewBillingLeadRepository()
	_ = repository.NewBillingMessageRepository()
	_ = repository.NewBillingMetricRepository()
	_ = repository.NewBillingMilestoneRepository()
	_ = repository.NewBillingNotificationRepository()
	_ = repository.NewBillingOrderRepository()
	_ = repository.NewBillingOrganizationRepository()
	_ = repository.NewBillingPaymentRepository()
	_ = repository.NewBillingPermissionRepository()
	_ = repository.NewBillingPipelineRepository()
	_ = repository.NewBillingPolicyRepository()
	_ = repository.NewBillingProductRepository()
	_ = repository.NewBillingProjectRepository()
	_ = repository.NewBillingQuotaRepository()
	_ = repository.NewBillingReservationRepository()
	_ = repository.NewBillingReviewRepository()
	_ = repository.NewBillingRewardRepository()
	_ = repository.NewBillingRoleRepository()
	_ = repository.NewBillingRuleRepository()
	_ = repository.NewBillingScheduleRepository()
	_ = repository.NewBillingSegmentRepository()
	_ = repository.NewBillingSessionRepository()
	_ = repository.NewBillingShipmentRepository()
	_ = repository.NewBillingSnapshotRepository()
	_ = repository.NewBillingSubscriptionRepository()
	_ = repository.NewBillingSurveyRepository()
	_ = repository.NewBillingTaskRepository()
	_ = repository.NewBillingTeamRepository()
	_ = repository.NewBillingTemplateRepository()
	_ = repository.NewBillingTicketRepository()
	_ = repository.NewBillingTransactionRepository()
	_ = repository.NewBillingUserRepository()
	_ = repository.NewBillingVenueRepository()
	_ = repository.NewBillingWarehouseRepository()
	_ = repository.NewBillingWebhookRepository()
	_ = repository.NewBillingWorkflowRepository()
	_ = repository.NewBookingRepository()
	_ = repository.NewBudgetRepository()
	_ = repository.NewCampaignRepository()
	_ = repository.NewCategoryRepository()
	_ = repository.NewCertificateRepository()
	_ = repository.NewChannelRepository()
	_ = repository.NewCommentRepository()
	_ = repository.NewContractRepository()
	_ = repository.NewCustomerRepository()
	_ = repository.NewDepartmentRepository()
	_ = repository.NewDeploymentRepository()
	_ = repository.NewDiscountRepository()
	_ = repository.NewDocumentRepository()
	_ = repository.NewEmployeeRepository()
	_ = repository.NewEndpointRepository()
	_ = repository.NewEventRepository()
	_ = repository.NewExpenseRepository()
	_ = repository.NewExperimentRepository()
	_ = repository.NewFeatureRepository()
	_ = repository.NewFeedbackRepository()
	_ = repository.NewInventoryAccountRepository()
	_ = repository.NewInventoryAchievementRepository()
	_ = repository.NewInventoryAlertRepository()
	_ = repository.NewInventoryBookingRepository()
	_ = repository.NewInventoryBudgetRepository()
	_ = repository.NewInventoryCampaignRepository()
	_ = repository.NewInventoryCategoryRepository()
	_ = repository.NewInventoryCertificateRepository()
	_ = repository.NewInventoryChannelRepository()
	_ = repository.NewInventoryCommentRepository()
	_ = repository.NewInventoryCustomerRepository()
	_ = repository.NewInventoryDepartmentRepository()
	_ = repository.NewInventoryDiscountRepository()
	_ = repository.NewInventoryEmployeeRepository()
	_ = repository.NewInventoryEndpointRepository()
	_ = repository.NewInventoryEventRepository()
	_ = repository.NewInventoryExpenseRepository()
	_ = repository.NewInventoryFeatureRepository()
	_ = repository.NewInventoryFeedbackRepository()
	_ = repository.NewInventoryInvoiceRepository()
	_ = repository.NewInventoryMessageRepository()
	_ = repository.NewInventoryMetricRepository()
	_ = repository.NewInventoryMilestoneRepository()
	_ = repository.NewInventoryNotificationRepository()
	_ = repository.NewInventoryOrderRepository()
	_ = repository.NewInventoryOrganizationRepository()
	_ = repository.NewInventoryPaymentRepository()
	_ = repository.NewInventoryPermissionRepository()
	_ = repository.NewInventoryPipelineRepository()
	_ = repository.NewInventoryPolicyRepository()
	_ = repository.NewInventoryProductRepository()
	_ = repository.NewInventoryProjectRepository()
	_ = repository.NewInventoryQuotaRepository()
	_ = repository.NewInventoryReservationRepository()
	_ = repository.NewInventoryReviewRepository()
	_ = repository.NewInventoryRewardRepository()
	_ = repository.NewInventoryRoleRepository()
	_ = repository.NewInventoryRuleRepository()
	_ = repository.NewInventoryScheduleRepository()
	_ = repository.NewInventorySessionRepository()
	_ = repository.NewInventoryShipmentRepository()
	_ = repository.NewInventorySnapshotRepository()
	_ = repository.NewInventorySubscriptionRepository()
	_ = repository.NewInventorySurveyRepository()
	_ = repository.NewInventoryTaskRepository()
	_ = repository.NewInventoryTeamRepository()
	_ = repository.NewInventoryTemplateRepository()
	_ = repository.NewInventoryTicketRepository()
	_ = repository.NewInventoryTransactionRepository()
	_ = repository.NewInventoryUserRepository()
	_ = repository.NewInventoryVenueRepository()
	_ = repository.NewInventoryWarehouseRepository()
	_ = repository.NewInventoryWebhookRepository()
	_ = repository.NewInventoryWorkflowRepository()
	_ = repository.NewInvoiceRepository()
	_ = repository.NewLeadRepository()
	_ = repository.NewMessageRepository()
	_ = repository.NewMetricRepository()
	_ = repository.NewMilestoneRepository()
	_ = repository.NewNotificationRepository()
	_ = repository.NewOrderRepository()
	_ = repository.NewOrganizationRepository()
	_ = repository.NewPaymentRepository()
	_ = repository.NewPermissionRepository()
	_ = repository.NewPipelineRepository()
	_ = repository.NewPolicyRepository()
	_ = repository.NewProductRepository()
	_ = repository.NewProjectRepository()
	_ = repository.NewQuotaRepository()
	_ = repository.NewReservationRepository()
	_ = repository.NewReviewRepository()
	_ = repository.NewRewardRepository()
	_ = repository.NewRoleRepository()
	_ = repository.NewRuleRepository()
	_ = repository.NewScheduleRepository()
	_ = repository.NewSegmentRepository()
	_ = repository.NewSessionRepository()
	_ = repository.NewShipmentRepository()
	_ = repository.NewShippingAccountRepository()
	_ = repository.NewShippingAchievementRepository()
	_ = repository.NewShippingAlertRepository()
	_ = repository.NewShippingAudienceRepository()
	_ = repository.NewShippingBookingRepository()
	_ = repository.NewShippingBudgetRepository()
	_ = repository.NewShippingCampaignRepository()
	_ = repository.NewShippingCategoryRepository()
	_ = repository.NewShippingCertificateRepository()
	_ = repository.NewShippingChannelRepository()
	_ = repository.NewShippingCommentRepository()
	_ = repository.NewShippingContractRepository()
	_ = repository.NewShippingCustomerRepository()
	_ = repository.NewShippingDepartmentRepository()
	_ = repository.NewShippingDeploymentRepository()
	_ = repository.NewShippingDiscountRepository()
	_ = repository.NewShippingDocumentRepository()
	_ = repository.NewShippingEmployeeRepository()
	_ = repository.NewShippingEndpointRepository()
	_ = repository.NewShippingEventRepository()
	_ = repository.NewShippingExpenseRepository()
	_ = repository.NewShippingExperimentRepository()
	_ = repository.NewShippingFeatureRepository()
	_ = repository.NewShippingFeedbackRepository()
	_ = repository.NewShippingInvoiceRepository()
	_ = repository.NewShippingLeadRepository()
	_ = repository.NewShippingMessageRepository()
	_ = repository.NewShippingMetricRepository()
	_ = repository.NewShippingMilestoneRepository()
	_ = repository.NewShippingNotificationRepository()
	_ = repository.NewShippingOrderRepository()
	_ = repository.NewShippingOrganizationRepository()
	_ = repository.NewShippingPaymentRepository()
	_ = repository.NewShippingPermissionRepository()
	_ = repository.NewShippingPipelineRepository()
	_ = repository.NewShippingPolicyRepository()
	_ = repository.NewShippingProductRepository()
	_ = repository.NewShippingProjectRepository()
	_ = repository.NewShippingQuotaRepository()
	_ = repository.NewShippingReservationRepository()
	_ = repository.NewShippingReviewRepository()
	_ = repository.NewShippingRewardRepository()
	_ = repository.NewShippingRoleRepository()
	_ = repository.NewShippingRuleRepository()
	_ = repository.NewShippingScheduleRepository()
	_ = repository.NewShippingSegmentRepository()
	_ = repository.NewShippingSessionRepository()
	_ = repository.NewShippingShipmentRepository()
	_ = repository.NewShippingSnapshotRepository()
	_ = repository.NewShippingSubscriptionRepository()
	_ = repository.NewShippingSurveyRepository()
	_ = repository.NewShippingTaskRepository()
	_ = repository.NewShippingTeamRepository()
	_ = repository.NewShippingTemplateRepository()
	_ = repository.NewShippingTicketRepository()
	_ = repository.NewShippingTransactionRepository()
	_ = repository.NewShippingUserRepository()
	_ = repository.NewShippingVenueRepository()
	_ = repository.NewShippingWarehouseRepository()
	_ = repository.NewShippingWebhookRepository()
	_ = repository.NewShippingWorkflowRepository()
	_ = repository.NewSnapshotRepository()
	_ = repository.NewSubscriptionRepository()
	_ = repository.NewSurveyRepository()
	_ = repository.NewTaskRepository()
	_ = repository.NewTeamRepository()
	_ = repository.NewTemplateRepository()
	_ = repository.NewTicketRepository()
	_ = repository.NewTransactionRepository()
	_ = repository.NewUserRepository()
	_ = repository.NewVenueRepository()
	_ = repository.NewWarehouseRepository()
	_ = repository.NewWebhookRepository()
	_ = repository.NewWorkflowRepository()
}
