package main

import (
	"net/http"
	"goober-go/internal/handlers"
	"goober-go/internal/services"
	"goober-go/internal/repository"
)

func registerInternalRoutes(mux *http.ServeMux) {
	handlers.NewAccountHandler("/api/account").RegisterRoutes(mux)
	handlers.NewAchievementHandler("/api/achievement").RegisterRoutes(mux)
	handlers.NewAlertHandler("/api/alert").RegisterRoutes(mux)
	handlers.NewAudienceHandler("/api/audience").RegisterRoutes(mux)
	handlers.NewBillingAccountHandler("/api/billing_account").RegisterRoutes(mux)
	handlers.NewBillingAchievementHandler("/api/billing_achievement").RegisterRoutes(mux)
	handlers.NewBillingAlertHandler("/api/billing_alert").RegisterRoutes(mux)
	handlers.NewBillingAudienceHandler("/api/billing_audience").RegisterRoutes(mux)
	handlers.NewBillingBookingHandler("/api/billing_booking").RegisterRoutes(mux)
	handlers.NewBillingBudgetHandler("/api/billing_budget").RegisterRoutes(mux)
	handlers.NewBillingCampaignHandler("/api/billing_campaign").RegisterRoutes(mux)
	handlers.NewBillingCategoryHandler("/api/billing_category").RegisterRoutes(mux)
	handlers.NewBillingCertificateHandler("/api/billing_certificate").RegisterRoutes(mux)
	handlers.NewBillingChannelHandler("/api/billing_channel").RegisterRoutes(mux)
	handlers.NewBillingCommentHandler("/api/billing_comment").RegisterRoutes(mux)
	handlers.NewBillingContractHandler("/api/billing_contract").RegisterRoutes(mux)
	handlers.NewBillingCustomerHandler("/api/billing_customer").RegisterRoutes(mux)
	handlers.NewBillingDepartmentHandler("/api/billing_department").RegisterRoutes(mux)
	handlers.NewBillingDeploymentHandler("/api/billing_deployment").RegisterRoutes(mux)
	handlers.NewBillingDiscountHandler("/api/billing_discount").RegisterRoutes(mux)
	handlers.NewBillingDocumentHandler("/api/billing_document").RegisterRoutes(mux)
	handlers.NewBillingEmployeeHandler("/api/billing_employee").RegisterRoutes(mux)
	handlers.NewBillingEndpointHandler("/api/billing_endpoint").RegisterRoutes(mux)
	handlers.NewBillingEventHandler("/api/billing_event").RegisterRoutes(mux)
	handlers.NewBillingExpenseHandler("/api/billing_expense").RegisterRoutes(mux)
	handlers.NewBillingFeatureHandler("/api/billing_feature").RegisterRoutes(mux)
	handlers.NewBillingFeedbackHandler("/api/billing_feedback").RegisterRoutes(mux)
	handlers.NewBillingInvoiceHandler("/api/billing_invoice").RegisterRoutes(mux)
	handlers.NewBillingLeadHandler("/api/billing_lead").RegisterRoutes(mux)
	handlers.NewBillingMessageHandler("/api/billing_message").RegisterRoutes(mux)
	handlers.NewBillingMetricHandler("/api/billing_metric").RegisterRoutes(mux)
	handlers.NewBillingMilestoneHandler("/api/billing_milestone").RegisterRoutes(mux)
	handlers.NewBillingNotificationHandler("/api/billing_notification").RegisterRoutes(mux)
	handlers.NewBillingOrderHandler("/api/billing_order").RegisterRoutes(mux)
	handlers.NewBillingOrganizationHandler("/api/billing_organization").RegisterRoutes(mux)
	handlers.NewBillingPaymentHandler("/api/billing_payment").RegisterRoutes(mux)
	handlers.NewBillingPermissionHandler("/api/billing_permission").RegisterRoutes(mux)
	handlers.NewBillingPipelineHandler("/api/billing_pipeline").RegisterRoutes(mux)
	handlers.NewBillingPolicyHandler("/api/billing_policy").RegisterRoutes(mux)
	handlers.NewBillingProductHandler("/api/billing_product").RegisterRoutes(mux)
	handlers.NewBillingProjectHandler("/api/billing_project").RegisterRoutes(mux)
	handlers.NewBillingQuotaHandler("/api/billing_quota").RegisterRoutes(mux)
	handlers.NewBillingReservationHandler("/api/billing_reservation").RegisterRoutes(mux)
	handlers.NewBillingReviewHandler("/api/billing_review").RegisterRoutes(mux)
	handlers.NewBillingRewardHandler("/api/billing_reward").RegisterRoutes(mux)
	handlers.NewBillingRoleHandler("/api/billing_role").RegisterRoutes(mux)
	handlers.NewBillingRuleHandler("/api/billing_rule").RegisterRoutes(mux)
	handlers.NewBillingScheduleHandler("/api/billing_schedule").RegisterRoutes(mux)
	handlers.NewBillingSegmentHandler("/api/billing_segment").RegisterRoutes(mux)
	handlers.NewBillingSessionHandler("/api/billing_session").RegisterRoutes(mux)
	handlers.NewBillingShipmentHandler("/api/billing_shipment").RegisterRoutes(mux)
	handlers.NewBillingSnapshotHandler("/api/billing_snapshot").RegisterRoutes(mux)
	handlers.NewBillingSubscriptionHandler("/api/billing_subscription").RegisterRoutes(mux)
	handlers.NewBillingSurveyHandler("/api/billing_survey").RegisterRoutes(mux)
	handlers.NewBillingTaskHandler("/api/billing_task").RegisterRoutes(mux)
	handlers.NewBillingTeamHandler("/api/billing_team").RegisterRoutes(mux)
	handlers.NewBillingTemplateHandler("/api/billing_template").RegisterRoutes(mux)
	handlers.NewBillingTicketHandler("/api/billing_ticket").RegisterRoutes(mux)
	handlers.NewBillingTransactionHandler("/api/billing_transaction").RegisterRoutes(mux)
	handlers.NewBillingUserHandler("/api/billing_user").RegisterRoutes(mux)
	handlers.NewBillingVenueHandler("/api/billing_venue").RegisterRoutes(mux)
	handlers.NewBillingWarehouseHandler("/api/billing_warehouse").RegisterRoutes(mux)
	handlers.NewBillingWebhookHandler("/api/billing_webhook").RegisterRoutes(mux)
	handlers.NewBillingWorkflowHandler("/api/billing_workflow").RegisterRoutes(mux)
	handlers.NewBookingHandler("/api/booking").RegisterRoutes(mux)
	handlers.NewBudgetHandler("/api/budget").RegisterRoutes(mux)
	handlers.NewCampaignHandler("/api/campaign").RegisterRoutes(mux)
	handlers.NewCategoryHandler("/api/category").RegisterRoutes(mux)
	handlers.NewCertificateHandler("/api/certificate").RegisterRoutes(mux)
	handlers.NewChannelHandler("/api/channel").RegisterRoutes(mux)
	handlers.NewCommentHandler("/api/comment").RegisterRoutes(mux)
	handlers.NewContractHandler("/api/contract").RegisterRoutes(mux)
	handlers.NewCustomerHandler("/api/customer").RegisterRoutes(mux)
	handlers.NewDepartmentHandler("/api/department").RegisterRoutes(mux)
	handlers.NewDeploymentHandler("/api/deployment").RegisterRoutes(mux)
	handlers.NewDiscountHandler("/api/discount").RegisterRoutes(mux)
	handlers.NewDocumentHandler("/api/document").RegisterRoutes(mux)
	handlers.NewEmployeeHandler("/api/employee").RegisterRoutes(mux)
	handlers.NewEndpointHandler("/api/endpoint").RegisterRoutes(mux)
	handlers.NewEventHandler("/api/event").RegisterRoutes(mux)
	handlers.NewExpenseHandler("/api/expense").RegisterRoutes(mux)
	handlers.NewExperimentHandler("/api/experiment").RegisterRoutes(mux)
	handlers.NewFeatureHandler("/api/feature").RegisterRoutes(mux)
	handlers.NewFeedbackHandler("/api/feedback").RegisterRoutes(mux)
	handlers.NewInvoiceHandler("/api/invoice").RegisterRoutes(mux)
	handlers.NewLeadHandler("/api/lead").RegisterRoutes(mux)
	handlers.NewMessageHandler("/api/message").RegisterRoutes(mux)
	handlers.NewMetricHandler("/api/metric").RegisterRoutes(mux)
	handlers.NewMilestoneHandler("/api/milestone").RegisterRoutes(mux)
	handlers.NewNotificationHandler("/api/notification").RegisterRoutes(mux)
	handlers.NewOrderHandler("/api/order").RegisterRoutes(mux)
	handlers.NewOrganizationHandler("/api/organization").RegisterRoutes(mux)
	handlers.NewPaymentHandler("/api/payment").RegisterRoutes(mux)
	handlers.NewPermissionHandler("/api/permission").RegisterRoutes(mux)
	handlers.NewPipelineHandler("/api/pipeline").RegisterRoutes(mux)
	handlers.NewPolicyHandler("/api/policy").RegisterRoutes(mux)
	handlers.NewProductHandler("/api/product").RegisterRoutes(mux)
	handlers.NewProjectHandler("/api/project").RegisterRoutes(mux)
	handlers.NewQuotaHandler("/api/quota").RegisterRoutes(mux)
	handlers.NewReservationHandler("/api/reservation").RegisterRoutes(mux)
	handlers.NewReviewHandler("/api/review").RegisterRoutes(mux)
	handlers.NewRewardHandler("/api/reward").RegisterRoutes(mux)
	handlers.NewRoleHandler("/api/role").RegisterRoutes(mux)
	handlers.NewRuleHandler("/api/rule").RegisterRoutes(mux)
	handlers.NewScheduleHandler("/api/schedule").RegisterRoutes(mux)
	handlers.NewSegmentHandler("/api/segment").RegisterRoutes(mux)
	handlers.NewSessionHandler("/api/session").RegisterRoutes(mux)
	handlers.NewShipmentHandler("/api/shipment").RegisterRoutes(mux)
	handlers.NewSnapshotHandler("/api/snapshot").RegisterRoutes(mux)
	handlers.NewSubscriptionHandler("/api/subscription").RegisterRoutes(mux)
	handlers.NewSurveyHandler("/api/survey").RegisterRoutes(mux)
	handlers.NewTaskHandler("/api/task").RegisterRoutes(mux)
	handlers.NewTeamHandler("/api/team").RegisterRoutes(mux)
	handlers.NewTemplateHandler("/api/template").RegisterRoutes(mux)
	handlers.NewTicketHandler("/api/ticket").RegisterRoutes(mux)
	handlers.NewTransactionHandler("/api/transaction").RegisterRoutes(mux)
	handlers.NewUserHandler("/api/user").RegisterRoutes(mux)
	handlers.NewVenueHandler("/api/venue").RegisterRoutes(mux)
	handlers.NewWarehouseHandler("/api/warehouse").RegisterRoutes(mux)
	handlers.NewWebhookHandler("/api/webhook").RegisterRoutes(mux)
	handlers.NewWorkflowHandler("/api/workflow").RegisterRoutes(mux)

	_ = services.NewAccountService()
	_ = services.NewAchievementService()
	_ = services.NewAlertService()
	_ = services.NewAudienceService()
	_ = services.NewBillingAccountService()
	_ = services.NewBillingAchievementService()
	_ = services.NewBillingAlertService()
	_ = services.NewBillingBookingService()
	_ = services.NewBillingBudgetService()
	_ = services.NewBillingCampaignService()
	_ = services.NewBillingCategoryService()
	_ = services.NewBillingCertificateService()
	_ = services.NewBillingChannelService()
	_ = services.NewBillingCommentService()
	_ = services.NewBillingContractService()
	_ = services.NewBillingCustomerService()
	_ = services.NewBillingDepartmentService()
	_ = services.NewBillingDeploymentService()
	_ = services.NewBillingDiscountService()
	_ = services.NewBillingDocumentService()
	_ = services.NewBillingEmployeeService()
	_ = services.NewBillingEndpointService()
	_ = services.NewBillingEventService()
	_ = services.NewBillingExpenseService()
	_ = services.NewBillingFeatureService()
	_ = services.NewBillingFeedbackService()
	_ = services.NewBillingInvoiceService()
	_ = services.NewBillingLeadService()
	_ = services.NewBillingMessageService()
	_ = services.NewBillingMetricService()
	_ = services.NewBillingMilestoneService()
	_ = services.NewBillingNotificationService()
	_ = services.NewBillingOrderService()
	_ = services.NewBillingOrganizationService()
	_ = services.NewBillingPaymentService()
	_ = services.NewBillingPermissionService()
	_ = services.NewBillingPipelineService()
	_ = services.NewBillingPolicyService()
	_ = services.NewBillingProductService()
	_ = services.NewBillingProjectService()
	_ = services.NewBillingQuotaService()
	_ = services.NewBillingReservationService()
	_ = services.NewBillingReviewService()
	_ = services.NewBillingRewardService()
	_ = services.NewBillingRoleService()
	_ = services.NewBillingRuleService()
	_ = services.NewBillingScheduleService()
	_ = services.NewBillingSegmentService()
	_ = services.NewBillingSessionService()
	_ = services.NewBillingShipmentService()
	_ = services.NewBillingSnapshotService()
	_ = services.NewBillingSubscriptionService()
	_ = services.NewBillingSurveyService()
	_ = services.NewBillingTaskService()
	_ = services.NewBillingTeamService()
	_ = services.NewBillingTemplateService()
	_ = services.NewBillingTicketService()
	_ = services.NewBillingTransactionService()
	_ = services.NewBillingUserService()
	_ = services.NewBillingVenueService()
	_ = services.NewBillingWarehouseService()
	_ = services.NewBillingWebhookService()
	_ = services.NewBillingWorkflowService()
	_ = services.NewBookingService()
	_ = services.NewBudgetService()
	_ = services.NewCampaignService()
	_ = services.NewCategoryService()
	_ = services.NewCertificateService()
	_ = services.NewChannelService()
	_ = services.NewCommentService()
	_ = services.NewContractService()
	_ = services.NewCustomerService()
	_ = services.NewDepartmentService()
	_ = services.NewDeploymentService()
	_ = services.NewDiscountService()
	_ = services.NewDocumentService()
	_ = services.NewEmployeeService()
	_ = services.NewEndpointService()
	_ = services.NewEventService()
	_ = services.NewExpenseService()
	_ = services.NewExperimentService()
	_ = services.NewFeatureService()
	_ = services.NewFeedbackService()
	_ = services.NewInvoiceService()
	_ = services.NewLeadService()
	_ = services.NewMessageService()
	_ = services.NewMetricService()
	_ = services.NewMilestoneService()
	_ = services.NewNotificationService()
	_ = services.NewOrderService()
	_ = services.NewOrganizationService()
	_ = services.NewPaymentService()
	_ = services.NewPermissionService()
	_ = services.NewPipelineService()
	_ = services.NewPolicyService()
	_ = services.NewProductService()
	_ = services.NewProjectService()
	_ = services.NewQuotaService()
	_ = services.NewReservationService()
	_ = services.NewReviewService()
	_ = services.NewRewardService()
	_ = services.NewRoleService()
	_ = services.NewRuleService()
	_ = services.NewScheduleService()
	_ = services.NewSegmentService()
	_ = services.NewSessionService()
	_ = services.NewShipmentService()
	_ = services.NewSnapshotService()
	_ = services.NewSubscriptionService()
	_ = services.NewSurveyService()
	_ = services.NewTaskService()
	_ = services.NewTeamService()
	_ = services.NewTemplateService()
	_ = services.NewTicketService()
	_ = services.NewTransactionService()
	_ = services.NewUserService()
	_ = services.NewVenueService()
	_ = services.NewWarehouseService()
	_ = services.NewWebhookService()
	_ = services.NewWorkflowService()

	_ = repository.NewAccountRepository()
	_ = repository.NewAchievementRepository()
	_ = repository.NewAlertRepository()
	_ = repository.NewAudienceRepository()
	_ = repository.NewBillingAccountRepository()
	_ = repository.NewBillingAchievementRepository()
	_ = repository.NewBillingAlertRepository()
	_ = repository.NewBillingBookingRepository()
	_ = repository.NewBillingBudgetRepository()
	_ = repository.NewBillingCampaignRepository()
	_ = repository.NewBillingCategoryRepository()
	_ = repository.NewBillingCertificateRepository()
	_ = repository.NewBillingChannelRepository()
	_ = repository.NewBillingCommentRepository()
	_ = repository.NewBillingContractRepository()
	_ = repository.NewBillingCustomerRepository()
	_ = repository.NewBillingDepartmentRepository()
	_ = repository.NewBillingDeploymentRepository()
	_ = repository.NewBillingDiscountRepository()
	_ = repository.NewBillingDocumentRepository()
	_ = repository.NewBillingEmployeeRepository()
	_ = repository.NewBillingEndpointRepository()
	_ = repository.NewBillingEventRepository()
	_ = repository.NewBillingExpenseRepository()
	_ = repository.NewBillingFeatureRepository()
	_ = repository.NewBillingFeedbackRepository()
	_ = repository.NewBillingInvoiceRepository()
	_ = repository.NewBillingLeadRepository()
	_ = repository.NewBillingMessageRepository()
	_ = repository.NewBillingMetricRepository()
	_ = repository.NewBillingMilestoneRepository()
	_ = repository.NewBillingNotificationRepository()
	_ = repository.NewBillingOrderRepository()
	_ = repository.NewBillingOrganizationRepository()
	_ = repository.NewBillingPaymentRepository()
	_ = repository.NewBillingPermissionRepository()
	_ = repository.NewBillingPipelineRepository()
	_ = repository.NewBillingPolicyRepository()
	_ = repository.NewBillingProductRepository()
	_ = repository.NewBillingProjectRepository()
	_ = repository.NewBillingQuotaRepository()
	_ = repository.NewBillingReservationRepository()
	_ = repository.NewBillingReviewRepository()
	_ = repository.NewBillingRewardRepository()
	_ = repository.NewBillingRoleRepository()
	_ = repository.NewBillingRuleRepository()
	_ = repository.NewBillingScheduleRepository()
	_ = repository.NewBillingSegmentRepository()
	_ = repository.NewBillingSessionRepository()
	_ = repository.NewBillingShipmentRepository()
	_ = repository.NewBillingSnapshotRepository()
	_ = repository.NewBillingSubscriptionRepository()
	_ = repository.NewBillingSurveyRepository()
	_ = repository.NewBillingTaskRepository()
	_ = repository.NewBillingTeamRepository()
	_ = repository.NewBillingTemplateRepository()
	_ = repository.NewBillingTicketRepository()
	_ = repository.NewBillingTransactionRepository()
	_ = repository.NewBillingUserRepository()
	_ = repository.NewBillingVenueRepository()
	_ = repository.NewBillingWarehouseRepository()
	_ = repository.NewBillingWebhookRepository()
	_ = repository.NewBillingWorkflowRepository()
	_ = repository.NewBookingRepository()
	_ = repository.NewBudgetRepository()
	_ = repository.NewCampaignRepository()
	_ = repository.NewCategoryRepository()
	_ = repository.NewCertificateRepository()
	_ = repository.NewChannelRepository()
	_ = repository.NewCommentRepository()
	_ = repository.NewContractRepository()
	_ = repository.NewCustomerRepository()
	_ = repository.NewDepartmentRepository()
	_ = repository.NewDeploymentRepository()
	_ = repository.NewDiscountRepository()
	_ = repository.NewDocumentRepository()
	_ = repository.NewEmployeeRepository()
	_ = repository.NewEndpointRepository()
	_ = repository.NewEventRepository()
	_ = repository.NewExpenseRepository()
	_ = repository.NewExperimentRepository()
	_ = repository.NewFeatureRepository()
	_ = repository.NewFeedbackRepository()
	_ = repository.NewInvoiceRepository()
	_ = repository.NewLeadRepository()
	_ = repository.NewMessageRepository()
	_ = repository.NewMetricRepository()
	_ = repository.NewMilestoneRepository()
	_ = repository.NewNotificationRepository()
	_ = repository.NewOrderRepository()
	_ = repository.NewOrganizationRepository()
	_ = repository.NewPaymentRepository()
	_ = repository.NewPermissionRepository()
	_ = repository.NewPipelineRepository()
	_ = repository.NewPolicyRepository()
	_ = repository.NewProductRepository()
	_ = repository.NewProjectRepository()
	_ = repository.NewQuotaRepository()
	_ = repository.NewReservationRepository()
	_ = repository.NewReviewRepository()
	_ = repository.NewRewardRepository()
	_ = repository.NewRoleRepository()
	_ = repository.NewRuleRepository()
	_ = repository.NewScheduleRepository()
	_ = repository.NewSegmentRepository()
	_ = repository.NewSessionRepository()
	_ = repository.NewShipmentRepository()
	_ = repository.NewSnapshotRepository()
	_ = repository.NewSubscriptionRepository()
	_ = repository.NewSurveyRepository()
	_ = repository.NewTaskRepository()
	_ = repository.NewTeamRepository()
	_ = repository.NewTemplateRepository()
	_ = repository.NewTicketRepository()
	_ = repository.NewTransactionRepository()
	_ = repository.NewUserRepository()
	_ = repository.NewVenueRepository()
	_ = repository.NewWarehouseRepository()
	_ = repository.NewWebhookRepository()
	_ = repository.NewWorkflowRepository()
}
